mysql:
  datasource:
    master:
      host: 127.0.0.1
      port: 3306
      user: root
      password: root
      url: charset=utf8&parseTime=true&loc=Local
      database: test
      load-gorm: true

    slave:
      host: 127.0.0.1
      port: 3306
      user: root
      password: root
      url: charset=utf8&parseTime=true&loc=Local
      database: test-1
      load-gorm: true
